[package]
name = "og_image_writer"
version = "0.0.1"
edition = "2018"
license = "../LICENSE"
keywords = ["open graphic", "image", "og", "canvas"]
categories = ["web-programming", "no-standard-library"]
readme = "../README.md"
repository="https://github.com/keiya01/og_image_writer"
description = "Generate an Open Graphic Image using a CSS-like API."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.0"
cairo-rs = { version = "0.14.3",  features = ["png"]}
