[package]
name = "og_image_writer"
version = "0.0.1"
edition = "2018"
license-file = "LICENSE"
keywords = ["open graphic", "image", "og", "canvas"]
categories = ["web-programming", "no-standard-library"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.17.0"
cairo-rs = { version = "0.14.3",  features = ["png"]}
